### ISSUE TITLE
Random results returned to a maximum

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#485] opened 2022-03-21 12:52 UTC
We are not telling users that their search has returned too many results.
Also, users seem to hit a ceiling of just under 3000 records with no transparency as to why the subset of results are chosen to be displayed, which makes it look like the dataset could be complete (but it isn’t, and we’re not alerting them).

Subset are random - do not cut off at a certain date, certain alphabetic name sequence, certain county or certain district, so there is no way for a user to know that the record they are searching for is missing.

**Comment by PatReynolds** [comment] 2022-03-21 17:42
Eg. a search of John Smith, any place, any date (whole database) and the same search restricted to Lancashire both return just below 3000 records.  There is no error warning.

@PatReynolds to ask Trustees with knowledge of FreeBMD for their advice

**Comment by PatReynolds** [comment] 2022-04-04 14:09
Emailed 4 April 2022

**Comment by PatReynolds** [comment] 2022-05-03 15:01
Ben replied 4th and 11th April.

**Comment by PatReynolds** [comment] 2022-05-03 16:23
@Vino-S to investigate

**Comment by richpomfret** [comment] 2022-06-13 16:15
@Vino-S can you take a look at this over the next sprint (time allowing)?

**Comment by PatReynolds** [comment] 2022-06-23 12:58
See Kirk's comment on 483 - we seem to need a way of getting the database to count and trigger a fail if it goes beyond a maximum.

**Comment by PatReynolds** [comment] 2022-07-21 13:23
Could we use the count on the page (e.g. 2945 results) to trigger displaying a too many results page (#483) at a lower number, e.g. 2701 results and above? What do you think @Vino-S

**Comment by richardofsussex** [comment] 2022-08-02 12:15
I'm happy to look into this @Vino-S @PatReynolds if you care to assign it to me.

**Comment by richardofsussex** [comment] 2022-08-02 14:51
I think the root of the problem is that we include a limit on the search itself - this is certainly true of REG and CEN searches. (This is why, in REG and CEN, you get the confusing message saying you found 500 records when in fact you will have found more than this.) See line 949 of app/models/search_query.rb for the relevant find() command. The result_count can only be exactly MAXIMUM_NUMBER_OF_RESULTS, or less than that number (500 for REG and CEN). It can't be more. The limit clause should be removed.

The routine which does BMD searches (freebmd_search_records) uses a rather different strategy. However, it finishes up with a call to records.take which does the same thing as the limit clause - it simply returns the first N records (in this case up to 3000). I suspect that some BMD records are missing a key piece of information (e.g. date), which is why the size of the result set subsequently drops from 3000 to a slightly smaller number (and therefore the 'too many results' message never appears). Again, commenting out the records.take line would test whether this theory is correct.

**Comment by richardofsussex** [comment] 2022-08-09 07:43
Further to this, I don't think that the fact that a search result is incomplete is a justification for showing the user _nothing_. It _is_ a justification for indicating that the results are incomplete, and for disabling the ability to sort the results. Since we are only showing a page of results at a time, the user will be used to the idea that they are not seeing _everything_ that might be relevant.

**Comment by richardofsussex** [comment] 2022-08-22 15:17
I have commented out that line in branch fb_485_rbl so we can test out this approach on a sensibly-sized test database (test3). The default local test data is tiny - impossible to reproduce the error. There is a commented-out line in search_queries/show.html.erb which gives the actual number of hits - you can see this by viewing the page source. Can we please put this into test3 so we can explore the effect of not throttling the number of results, response-wise?

**Comment by richardofsussex** [comment] 2022-09-12 15:08
OK, branch fb_485a_rbl contains what I hope is a better fix for this issue. The 'too many records' page should now appear - and it should report the actual number of records found. @Vino-S please put this branch into test3 for initial testing.

**Comment by DeniseColbert** [comment] 2022-11-01 15:44
@Vino-S to push to test3

**Comment by DeniseColbert** [comment] 2022-11-15 15:27
Maximum results showed has been increased to 50,000 so this issue should be fixed (search time changed from 300ms to 50 seconds too)

**Closed as completed** 2022-11-15 15:27 UTC
