### ISSUE TITLE
Implement 'report a data problem'

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#215] opened 2020-02-17 16:07 UTC

**Comment by PatReynolds** [comment] 2020-04-08 12:31
Tested 8/4/2020, but did not arrive on github as an issue.
Rather than being taken to a 'thank you' page, took me to the refinery page with "thank you for your feedback" at the top:
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/bf48ce75-feed-4ee5-8f6e-3d7471f6ab86)

**Comment by Captainkirkdawson** [comment] 2020-04-08 14:23
They never go onto github until reviewed by a system administration to confirm that it is an actual issue.
The feedback display has that as a specific action.

Cannot comment on  navigation after submission

**Comment by PatReynolds** [comment] 2020-04-08 15:28
Thanks, Kirk!  So, @Vino-S ,  just the page you are redirected to needs changing.

**Comment by Vino-S** [comment] 2020-05-19 15:25
ready for testing on test2

**Comment by richpomfret** [comment] 2020-05-19 16:27
@Vino-S to update TEST3 as our testing environment and we can begin using it as our primary testing environment.

**Comment by richpomfret** [comment] 2020-06-02 16:13
@Vino-S has this been updated? Let me know and i'll then test this.

**Comment by Vino-S** [comment] 2020-06-09 14:35
@richpomfret updated to test3

**Comment by DeniseColbert** [comment] 2020-06-16 11:51
I tested this and saw this screen after submission:
![image](https://user-images.githubusercontent.com/19173257/84769073-30cb2e80-afcd-11ea-854c-86751e604c22.png)

**I think the message is very easily missed.**

Also, I noticed in "Contacts" that there is the button to "Convert to issue on Github".

**EDIT- A story WAS created, it seems, but on FreeREG board**:

![image](https://user-images.githubusercontent.com/19173257/84770930-66bde200-afd0-11ea-8158-d8dc0fb4b4c0.png)


Also, the message went into my Spam folder:

![image](https://user-images.githubusercontent.com/19173257/84770783-1b0b3880-afd0-11ea-935e-cecee57b6251.png)

**Comment by Vino-S** [comment] 2020-07-03 13:27
Fixed. The issue is now created in BMD2 board. 

I haven't made changes for message display. Any suggestions would be helpful

**Comment by PatReynolds** [comment] 2020-07-16 11:29
Current system is  reached from the search detail page (ie as sytem planned here), and provides detailed instructions (which seem not to be read by some users) - https://www.freebmd.org.uk/cgi/corrections.pl?r=252876913&d=bmd_1593465254 and a form that contains the details from the entry in the detailed results page and provides the user with an opportunity to correct those details in a form.

A suggestion:
The 'report a data problem' takes the user to a number of option - each option is based on the user identifying what it is they want to do - and then receiving the information (or the form) rather than having a long text to read:
e.g "I want to change something to match what is on the certificate (or family bible or FreeREG, FreeCEN ..." does not go to a form but to an explanation.
I have divided the current explanations and form on this spreadsheet 
https://docs.google.com/spreadsheets/d/1VQt3Fjl1y2eixHsPQVp2gSZ0VEVPZ4xYsisbkLiZ01c/edit?usp=sharing

Please discuss on Slack whether this structure/pathway is what is needed, and on the spreadheet if it is (I have largely used the FreeBMD1 text, with some changes for clarity when seen in isolation and/or adding in 'next step'.

**Comment by richpomfret** [comment] 2020-10-21 16:42
Next steps - @DeniseColbert to take a look at FAQ on FR to see what they do and then assess in relation to BMD2.

**Comment by PatReynolds** [comment] 2020-10-22 10:54
Information copied from #354 which is for FreeCEN1 systems, not the new systems:
Version 1.2 of the FreeCEN Handbook is now available for download from test3. It still needs some revision in places but seems to be getting there. If you notice that something is missing please let me know. It has been proofread to page 35 only. It does not include all of the Managing County or Managing Syndicate functions.

There are also 2 other documents available from the same Handbook Page.
Ready Reference which is essentially a replacement for Fields.htm but does not replace the Handbook for some functions. I have tried to keep it as short as possible.
Quick Start Guide which is a short desktop reference for experienced transcribers.

We have taken onboard feedback over the original download page and there are now deatiled instructions on Downloading or Printing each document.

Geoff


richpomfret
commented on Oct 12, 2020
@AlOneill can you take a look at the latest draft and assess the changes/passive voice?


AlOneill
commented on Oct 12, 2020
@richpomfret @geoffj-FUG The page FreeCEN Handbook on t3 is not a draft (for obvious reasons, I guess) but it is not sync-ready as there is no layout and no proper headings (and maybe other problems — I have not read it properly, yet).

I'll get the page into shape first, and then have a look at the actual Handbook, if that is what you mean?


geoffj-FUG
commented on Oct 12, 2020
Alison

You are correct. The document on t3 is a pdf.

It is not a final draft. It is being written on the fly as things are tested and a process becomes clear.

To do otherwise would mean that we would miss things if we try to document the whole system when it is ready.

I have attached a document for you. It is an Abbreviated Handbook and is being looked at be a tester at the moment to make sure everything is covered.

This abbreviated handbook is now quite stable as it is for Transcribers and Proofreaders and we have moved on in testing from the content.

It is a subset of the Full Handbook. I was expanding the Ready Reference and got feedback on the format and we realised that we had almost achieved an Abbreviated Handbook. So that suddenly made sense.

I have attached the word version as it should be easier for you to use. The styles used are Headings 1 to 3 plus Normal and Notes plus TOC. All links should be in place.

Does this help?

Geoff





—


AlOneill
commented on Oct 13, 2020
I've fixed the basic HTML markup of the Refinery page, FreeCEN Handbook on t3 (i.e. not the Handbook itself or the Ready Reference or the Quick-start Guide, but the HTML page that is opened by the "FreeCEN Handbook" Action).

Next, I'll create a DRAFT version of the Refinery page that addresses other issues that I've spotted.

(I'll reply to @geoffj-FUG offline about reviewing the PDF documents — attachments do not survive.)


AlOneill
commented on Oct 13, 2020
The DRAFT version of the edited Refinery page, FreeCEN Handbook is ready for review.

The changes made are:

replace passive voice with active
acknowledge browser differences and non-Windows users
polish text for consistency and readability
Have I missed or distorted anything?


geoffj-FUG
commented on Oct 13, 2020
Alison

The Ready Reference has been replaced by the Abbreviated Handbook for England and Wales Transcribers and Proofreaders.

I have canned the Quickstart guide because the differences in the systems are significant and people will use it to take shortcuts.

The instructions for the Abbreviated Handbook are currently:

Abbreviated FreeCEN2 Handbook for England and Wales Transcribers and Proofreaders

The Abbreviated Handbook is an easy to use computer based or desktop reference. It is suitable for Transcribers, new Transcribers and Proofreaders working on England and Wales (including Isle of Man and the Channel Islands). It can be printed on A4 paper, either one sided or back to back.

    Select Download the Abbreviated Handbook
The Abbreviated Handbook will appear on your Screen in Acrobat Reader

    Select the Download Icon (An underlined downward arrow)
    You will be asked where you want to Save the Abbreviated Handbook. Save it.
    Open the Abbreviated Handbook in Acrobat Reader
    Select the Print Icon (or File … Print)
    Select your Printer
    Set Pages to Print to All
    If you want to Print on both sides of the paper, tick the Print on both sides of the paper box
    Set the Orientation to Portrait
    Select Print
The Abbreviated Handbook will now print. It contains about 60 pages (or 30 if printed back to back).

The Abbreviated Handbook may be updated from time to time. You will be advised when a new version of the Abbreviated Handbook becomes available.

Can you standardise these instructions for Refinery as you did for the Handbook, please?

Geoff

**Comment by DeniseColbert** [comment] 2020-10-30 16:01
Pat is suggesting that "Report a Data Problem" takes the user to a number of options with info rather than a contact form. IIUC this is similar to FreeREG FAQs. If we want to avoid the user having to read a lot of information (there are 17 questions), we perhaps need a contents section with anchors. FreeREG FAQs use a sidebar.

**Comment by geoffj-FUG** [comment] 2020-11-03 11:48
Pat
Can I look at this after I have everything ready for deployment please? I still have a bit of work to go.
Geoff

**Comment by Captainkirkdawson** [comment] 2020-11-03 15:02
@geoffj-FUG This story refers to FreeBMD2 not CEN but we should look at it over there as well

**Comment by PatReynolds** [comment] 2020-11-04 17:21
Denise to put the 17 questions into groups.

**Comment by DeniseColbert** [comment] 2021-01-27 16:29
First draft:
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/07bb6218-28ad-444f-a43c-fff3f1fd015e)

**Comment by richpomfret** [comment] 2021-01-27 17:52
Use FR/FC to guide design/User Experience here.

**Comment by DeniseColbert** [comment] 2021-03-04 14:01
FreeREG FAQ page looks like this: https://www.freereg.org.uk/cms/help/frequently-asked-questions-researchers

The categories in https://docs.google.com/spreadsheets/d/1VQt3Fjl1y2eixHsPQVp2gSZ0VEVPZ4xYsisbkLiZ01c/edit#gid=942996947&range=A1:E7 would be the items in the side menu.

@PhilipClarke712 you asked Pat about the size of the buttons for this IIUC, but we don't use buttons for this on FreeREG (which we're emulating for consistent aesthetic). Pat asked me to send to you the HTML of the FreeREG FAQ page so that you can take the info from the spreadsheet and create a similar page for FreeBMD2. I'll send the HTML file by email to your freeukgenealogy.org.uk account; let me know if you need anything clarifying.

**Comment by PatReynolds** [comment] 2021-04-13 16:45
Hi @Vino-S in designing this page, have you remembered it isn't like the set-up in FreeREG and FreeCEN, but a lower option from a number of reporting (see table Denise put in this issue 27 Jan)

**Comment by PhilipClarke712** [comment] 2021-04-13 19:34
Hi @PatReynolds 

I've got "my" html pages and images back on test3, I glad to say. So I can ask a question about your comment above to Vino-S.

I've got a draft html page  associated with this issue back on test3. It's probably 75+ % complete but I have not seen it for a few days; and its still unchecked by me. ( It's to be found  at https://test3.freebmd.org.uk/cms/help/draft-frequently-asked-questions-researchers ).

The Spreadsheet 1 rows 17 to 25, above,  imply a link to an Error Reporting Page and give various texts to put on that page. Is that what Vino-s is designing above, or is the Error Reporting Page referred to in the spreadsheet another html page for me to do?

Finally, ignoring any typos for now (I'll hopefully find and fix them), is the draft html page doing what was expected?

**Comment by DeniseColbert** [comment] 2021-04-26 17:10
Snip of updated categories:

![image](https://user-images.githubusercontent.com/19173257/116123188-9c385f00-a6ba-11eb-9b4a-7e8d0d7b734d.png)

**Comment by PhilipClarke712** [comment] 2021-04-26 21:14
Hi @DeniseColbert ,

Thanks for the snip, I've updated my draft page were necessary against the table above.

I have one question: in the https://www.freereg.org.uk/cms/help/frequently-asked-questions-researchers page given above as an example, if "your question" is not answered the FreeREG page leads you to https://www.freereg.org.uk/contacts/new 

FreeBMD2 test3 does not have an identical page, but the nearest ones seem to be: (if I'm **not logged** on) Report a Problem, or (if I **am logged** on) https://test3.freebmd.org.uk/contacts

However, the Report a Problem page appears to be very content-specific, if I'm logged on then my name, session id and other timestamps are recorded in the http address ( such as:  https://test3.freebmd.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2021-04-26+21%3A01%3A44+UTC&session_id=7f983925eef58493c06018481fc1b3b9&user_id=Philip+Clarke&problem_page_url=%2Fcms%2Finformation-for-coordinators&previous_page_url=https%3A%2F%2Ftest3.freebmd.org.uk%2Fcontacts&feedback_type=issue ) , but if I'm not logged in I only get Data Problem Report page (such as: https://test3.freebmd.org.uk/contacts/112640983/report_error?locale=en&query=60872ac4bd30f25017b5c12c ) .

So its no too obvious which page I should call up

**Comment by DeniseColbert** [comment] 2021-05-12 12:11
@PhilipClarke712 All good points! 

I missed out the first step in the process: e.g. FreeREG

![image](https://user-images.githubusercontent.com/19173257/117972142-a7c68f80-b322-11eb-8531-5dac2009a37a.png)

You can see that (when not logged in) there is a button above the table to Report an Error. This would take the user to your page that is similar in format to the FreeREG FAQs page, but has the title "Reporting Errors in Transcriptions" (unless there's a better one?) and content as per the spreadsheet. At the top of this page, the user should be able to select the nature of the error (perhaps a 'contents' area that jumps to the relevant part of the page?)

We really want to stress that they should only use the contact form if they are _absolutely sure_ that they have a legitimate correction that we can action. 

Hope this helps? Sorry for the confusion!

**Comment by PhilipClarke712** [comment] 2021-05-17 14:48
Hi @DeniseColbert,

Thanks for this info. 

I've renamed the page. A 1st draft version is now within the Help page hierarchy at https://test3.freebmd.org.uk/cms/help/draft-reporting-errors-in-transcriptions . I have a bit more work to do before handing it back.

It is done in the new "FAQ" format so there is a side navigation table, but problems are grouped together, as Missing Entry group , Problem with Individual group, Problem with District group, etc, so the navi-table takes you down to the level of a "group of related problems" rather than individual problems. The level of indexing can be increased, if you like, to the level of a question. but then that is going away from the FAQ style to just a page with a navigation panel. 

Note: from what what you describe above for FreeBMD2, the direction of flow would be from a button on an Entry Information page to this page. Clinking on the button would need to **open this help page in a new tab**, so that if, say the advice was to report the problem, the researcher can do it from either the search or the Entry Information page. The html page can't give an on-line form to report the error

**Comment by AlOneill** [comment] 2021-05-17 23:29
On the Detail page, I suggest that the link to the help page should be just that — a **link** — and I agree that it should open in a new tab (with a visible warning, of course!).

Use a **button** for the action that takes a user to the Data Problem Report page. This should also open in a new tab, so that the user can refer back to the suspect record when filling in the report details.

The trick will be to entice a user into read the info first! It will need a good sentence that includes the link and emphasises the benefits of reading the help page.

**Comment by PatReynolds** [comment] 2021-05-24 16:30
@PatReynolds to find an example page.

**Comment by Vino-S** [comment] 2021-07-05 13:52
Initial implementation is ready for testing in test3

**Comment by PatReynolds** [comment] 2021-07-05 14:34
Thanks Vino, looking good! 

A few text changes needed now we know what it will look like.  I think the text at the bottom is fine for those instances where submitting a report is what we want, but we might want to be more discouraging with those who shouldn't (perhaps "Yes, I have read the above explanation and understand that there is nothing to correct here, but still wish to submit a report" @AlOneill can you think of a better way of saying that ????

Maybe they all need to start "Please do not use this form to report that..." (if the "error" is such that it no report is needed).

Overall, I think the instructions to submit a report probably need @AlOneill 's eye on them.  Perhaps "please tick the box below and fill in the form which drops down beneath it"?

"the entry does not match what I know" - needs space  Postems(notes)  and everywhere Postems are mentioned for the first time it needs "(notes)" after it  Also needs "Please also see information on why the month may be "wrong" with link to Help page

"The month/quarter is wrong" - needs link to help page

"see here for help on finding a missing spouse".  needs link to help page 

"There are characters ...." start "If you have a legible copy ...." as a new paragraph

Suggested text for "I have checked the scan ...."
Thank you for checking the scan.  Please [standard instructions to fill in the report ]."

**Comment by AlOneill** [comment] 2021-07-10 11:03
I have concentrated on errors (grammatical and similar). Some of the text is formal and unfriendly but perhaps that is the aim?!?

Explanation 'i' button — suggest: Please read the explanation below for the selected query

A 0, list-item 2, space missing — Postems (notes)
A 0, last para, link-text, space missing and 'link' is superfluous — GRO (opens in new tab)

A 1, wrong use of 'may' and others — You could use a Postem (note) to provide the information which could help other family historians

A 6, hyphen used instead of em-dash — … a spouse search `&mdash;` see `<a href="/cms/help#findSpouse">finding a missing spouse</a>` for help

A 8, second part of answer not clear (to me!)

A 9, link missing `target="_blank"` and link-text missing warning — GRO website (opens in new tab) 

A 11, hyphen used instead of em-dash — … a transcription error `&mdash;` if this is the case, …

A 12, missing text? — please tick the 'Yes, I have read the explanation …' box below and use the form beneath it to give us the details

A 13, list-item 2, same issue with missing space as in A 0
A 13, same issue with link to GRO as in A 0

Q 14, missing word after "spouse's", maybe "first name" or "surname"?
A 14, list-item 2, same issue of missing space as in A 0
A 14, same issue with link to GRO as in A 0
A 14, opening para, "provide" rather than "provided" — However, we provide a number of …

Q 15, "the transcription does not match what has been transcribed" cannot be correct! Suggest: the transcription does not match what is on the scan

Tick-box — suggest: Yes, I have read the explanation above but I still wish to submit an error report

**In addition**, the form `id` and `for` label-input pairs do not match.

Link needed to month/quarter info as per Pat's request above: /cms/help#gtkResults

**Comment by AlOneill** [comment] 2021-07-10 11:07
There are a lot of twiddly edits to make here: It occurs to me that it might be easier if I edit the partial — just point me to the file.

**Comment by Vino-S** [comment] 2021-07-14 13:53
Hi @AlOneill
Below is the link to the Frequently asked questions HTML file:
https://github.com/FreeUKGen/MyopicVicar/blob/page_entries/public_site_specific/freebmd/faq.html.erb
Thank you very much for sorting this out.

**Comment by AlOneill** [comment] 2021-07-15 13:24
@Vino-S File edited and returned to you. Of course, that file does not include the 'Explanation' info button text or the label for the tick-box that reveals the form: see my previous comments, three posts above.

15th query — I've attempted to fill in the missing word after "spouse's", but have to admit that it was a shot in the dark! Anyone know what should go there?

@PatReynolds I did not add a link to Help for month/quarter issues as, on reflection, I do not think that Help adds anything material to the explanation given.

**Comment by PhilipClarke712** [comment] 2021-07-15 15:48
Try the original page https://www.freebmd.org.uk/search-results-help.html  from FreeBMD1

**Comment by AlOneill** [comment] 2021-07-15 20:41
On further reflection, I'm not at all happy about the 15th query,  currently:
"The entry for this event (for example, bride's surname at marriage) does not match the FreeBMD entry for another person at this event (for example, the spelling of her name in spouse's)."

Unless we can rewrite this to make sense, I suggest we delete it. The previous query seems to cover a similar territory?
There is nothing like it (as far as I can see) on the page you gave @PhilipClarke712

**Comment by PhilipClarke712** [comment] 2021-07-15 21:40
@AlOneill 
Sometime before I started (so pre-Feb. 2020) each item on the BMD1 FAQ page was marked as one of three classes: for **About**, for **Help**, or **not for Researchers**. So the Help-aspects of the original BMD1 FAQ page became a list of less than 41 items -possibly about 22 (at most) FAQs.

It looks like one or more people might have done a brain-storming session on the pared-down BMD1 FAQ Help questions. But, I agree what is written for 14th FAQ does not make any sense.

Note: Michael W Foster wrote two books on the GRO (_A comedy of errors_ is the main title of both volumes), he is believed to be the only non-employee who was allowed to do original research on their registers (registers and indexes) inside Southport. He gives examples where he believes that the vicar (against the rules and regulations) may have _filled in_ the register before the marriage took place, so the bride or groom's signature does not agree with their name as printed on the register. So, this might account for a two entries in the Index.  He gave (I think) a few examples were the name of the one the witnesses got entered as bride or groom; and the bride/ groom got entered as a witness. Brides (not applicable to me) would sign their maiden names, not the name of the husband they have just married; but, obviously, if she had been married before her surname would not be the same as her father's surname.

Perhaps, someone brain storming - not me - half remembered these errors and mis-transcribed them.

**Comment by AlOneill** [comment] 2021-07-15 21:59
@PhilipClarke712 The queries for the (app) 'Data problem report' page appear to be from the same source as the Refinery page: https://test3.freebmd.org.uk/cms/help-superseded-or-draft/draft-reporting-errors-in-transcriptions#individuals
See the 2nd entry.

You make an interesting observation above. Anyone want to have a go at re-wording the query (in the light of Philip's comment above, maybe)? Or do we delete it? Or try to find the original version?

@Vino-S What is the source of the GitHub page — do you know?

[edited]

**Comment by PatReynolds** [comment] 2021-07-19 11:30
The word that was escaping me was "accordion"

Example: https://www.all-clad.com/customer-service

Their contact page https://www.all-clad.com/contact is also good at sorting out queries to the right point / collecting the right data

Another (simpler) example
https://www.triodos.co.uk/individual (the "why bank with Triodos" section

Many firms are now going to block style with images and a very friendly tone, e.g. https://www.travelperk.com/resources/ 

https://www.berryinsurance.com/insurance-resources  is a completely different approach

**Comment by richpomfret** [comment] 2021-07-19 16:18
@AlOneill to have a play. @PatReynolds to create story to turn the form into an accordian style. We need basic functionality for MVP and accordian for future version/iteration.

**Comment by PatReynolds** [comment] 2021-07-19 16:26
Original text may be https://www.freebmd.org.uk/search-results-help.html

**Comment by AlOneill** [comment] 2021-07-19 17:21
@PatReynolds Sadly, not that file. Thank you for looking.

**Comment by richpomfret** [comment] 2021-08-02 16:41
@Vino-S to update the text, also to consider user cases/situations we either provide text for or do not, then we can close this.

**Comment by richpomfret** [comment] 2021-08-16 16:49
@PatReynolds to contact Allan about reporting a data problem (to review whether there is a pathway already for this).

**Comment by PhilipClarke712** [comment] 2021-08-16 18:46
If / when someone uses the Entry Information page on FreeBMD(1) to report a problem with a transcription that I (and that applies to other transcribers) transcribed, then my Syndicate Leader, I, or someone else, will be made aware that a change has been requested.  

Statistics can be found daily at https://www.freebmd.org.uk/cgi/correction-statistics.pl and the correction is managed at https://www.freebmd.org.uk/cgi/show-corrections.pl (which needs a valid log-on)

As records may be double-keyed that pathway has to determine which syndicate / transcriber should be made responsible for considering / actioning the change request.

I am not familiar with the pathway from Entry Information page to the correction system, but Allan and Barry will be. It replaced a live person and his own spreadsheets.

@PatReynolds My oldest correction goes back to 26/03/2014. I think it took two years to implement the new system. The late Kevin Howell was the Corrections Coordinator with the spreadsheet. Dave Mayall, on behalf of the trustees, reported his death. Something to consider for the News page. 

I'm pleased to note that someone did record the introduction of the corrections system on https://test3.freebmd.org.uk/cms/about/history  : in came into being in June 2015 - in half the time that I thought it took.

**Comment by PatReynolds** [comment] 2021-08-17 12:13
Asked Allan who we should liaise with 17 Aug 2021

**Comment by PatReynolds** [comment] 2021-08-18 16:15
Hi @Vino-S - pleaes could you contact Allan and Barrie for details of the system.

**Comment by DeniseColbert** [comment] 2021-09-16 15:43
I'll create a new story for page issues, as I don't want to derail this thread

**Comment by richpomfret** [comment] 2021-09-27 16:48
@Vino-S to now hook this up.

**Comment by Vino-S** [comment] 2021-10-25 15:24
Implementation of a form will be required in my opinion.
The form fields will be similar to that of the search form. The form fields will require validations for example Mother's name start quarter.

**Comment by PhilipClarke712** [comment] 2021-10-25 16:18
Or possibly two forms, depending on the request: 
(1) if an entry is missing then every applicable field (see below) will need to be inputted into a blank form; 
(2) but, if only one or two fields are wrong (say a typo in a Registration District), as I potential user I might like to have two forms side-by-side, one showing the current data and then other form being the one where I make a correction to one or more fields - (which is how is it is done on BMD(1)).

Mother's name is only provided in the GRO Index from the second Qtr of 1911, so I assume if the systems needs a validation check to done to stop the addition of the Mother's name prior to that quarter. Fair enough; but is the only one of the validation check that is needed.

For example a possibly tricky one to handle is where the GRO index states the mother's / spouse's name was (say) '**Smith or Jones**', then FreeBMD transcribers would record that as two separate entries one with the mother / spouse as  **Smith** and one with the mother / spouse as **Jones**. With a (hash)COMMENT(2) line of explanation between the two entries.  So, if I only found only one mother / spouse was indexed, (say) **Smith**, I could raise a 'data problem' which strictly is the addition of a second entry with the mother's / spouse's name **Jones**; not to change the original entry from **Smith** to **Smith or Jones** ; and the system creates the two (hash)COMMENTs - one attached to each entry. That I assume is a simple programming task to check that the requested change is compliant.

**Comment by PatReynolds** [comment] 2021-10-25 16:26
@PhilipClarke712 are you saying that if I enter "The mother's surname is wrong! This is me, and my mother was Susan Jones!!!!" the system will automatically say "The entry is Smith or Jones, and can be found as you can see in the image, and can be found by searching for both Smith and Jones, so no correction is needed".

**Comment by PhilipClarke712** [comment] 2021-10-25 16:54
@PatReynolds 

This is the problem with words and understanding. 

The answer to the precise example you gave above, the statement: "The mother's surname is wrong! This is me, and my mother was Susan Jones!!!!"  is --- **so what** we only provide what is in the GRO Index. We are not going to changing it on your say so - Of course there is a much more polite way of putting that. That can be found on FreeBMD(2) and hopefully on Beta.

I transcribe for FreeBMD(1) so I know the FreeBMD : Transcribers' Knowledge Base https://www.freebmd.org.uk/vol_faq.html almost off by heart. So, I am specifically referring to entries transcribed in accordance with https://www.freebmd.org.uk/vol_faq.html#6u 

My example (made up) is one that I might find in the GRO Index, of the form: Smith, Fred, Smith or Jones, somewhere, 10, 1066. 

That would be transcribed as two records 
Smith, Fred, Smith, 10, 1066
(hash)COMMENT(2) entry reads Smith or Jones for mother's / Spouse's (as appropriate) name
Smith, Fred, Jones, 10, 1066

If the transcriber enters that record wrongly, as a researcher I can request that the record(s) to be changed to what the GRO Index shows (subject to the changes that FreeBMD makes as per FAQ 6u) and my comment was intended to considered in that specific context. This has nothing to do with **The mother's surname is wrong! This is me, and my mother was Susan Jones!!!!**"

If you want a live example, or hundred, or a thousand, I will supply them

**Comment by PhilipClarke712** [comment] 2021-10-25 17:27
@PatReynolds 
I think this leads on to the big of question of how does the **change get made**?
If this was FreeBMD(1), anyone asking for such a change would need to fill in a form (a different form to what is on FreeBMD2) and that change request will go (by a path unknown to me) to the transcriber of the entry, the syndicate of the that transcriber, or someone else (a live person). We (a live person) don't get to see the justification "The mother's surname is wrong! This is me, and my mother was Susan Jones!!!!" , we only get to see the change request. I/we decided if the change is needed, we do it or not, and record our decision on the system. Is the FreeBMD2  system of doing the change going to automated?

Note: FreeBMD(1) is purposely obscure, if the form is not completed in the way the system demands, the form will not be accepted.

**Comment by geoffj-FUG** [comment] 2021-10-26 00:15
Pat

 

I know nothing about FreeBMD but looking at this simplistically I see an issue:

 

If I say my mothers name was Sally Jones  am I sure about that or does it come under heresay?

 

If a child was born out of wedlock to a married mother the child would be registered under the mother’s married name. The child may however be known in the community under the father’s name. If the mother and father are subsequently married the registration for the child may have been re-issued.

 

I know that the registration should show the maiden name but I have an example in our family tree where it was not. So the child thought that their mother was Sally Jones (her first married name) whereas the documentation should have shown Sally Surname, her maiden name.

 

So my question is how is the advice verified?

 

Geoff

**Comment by PhilipClarke712** [comment] 2021-10-26 06:41
@PatReynolds, @geoffj-FUG 

My response that generated the "heat" was to the comment from Vino-S about verifying the data that person wanting a request has to put on the form in order  for the system to accept the form. Vino-S specifically referred to the Mother's name and the GRO Indexes do not provide that data before the second half of 1911 - so we can't have people asking us to add data that is not in GRO Index, but they can use a Postem to provide it themselves.

On FreeBMD(1) a live person decides if they are going to do the requested change. It is clear from FreeBMD(1) that we will only correct our mistakes in the the GRO Index, we will not correct the GRO's mistakes.  Even if this woman "The mother's surname is wrong! This is me, and my mother was Susan Jones!!!!"  sends a copy of her mother's birth certificate, will we not correct the GRO's index. She needs to get the GRO to correct their index first and then when that is done, will we change our index. We will correct our mistakes.

I do hope that FreeBMD2 is not going down the path of machine-correction of our indexes, based on what someone asks us to do.

**Comment by geoffj-FUG** [comment] 2021-10-26 06:49
Philip

 

My comment was not intended as ‘heat’. I was being the devil’s advocate.

 

I agree with you that the GRO record should not be amended. I was simply outlining a scenario where a person may have an issue with the entry and was simply asking ‘ís it checked’? In the example case it is up to us to go back and say, you should consult all the birth certificates.

 

I apologise if my comment was taken the wrong way.

 

Geoff

**Comment by PatReynolds** [comment] 2021-10-26 08:55
Thanks for your useful input on this Philip and Geoff.

It seems on FreeBMD1 the system is set up to only take the facts of the change required (eg replace Jones with Smith) but no space for justification.

For Phase 3, the corrections system just needs to replicate the action of the form on FreeBMD1, but the system can be enhanced in Phase 5+.

**Comment by PhilipClarke712** [comment] 2021-10-26 14:06
To shed some light on this topic, I opened a change request on Edith Daisy Dent, on FreeBMD(1), printed it to Pdf and exited without submitting it. I know from long experience, that if  the form is not filled in correctly, the system will not accept it. There may a log file that records this failed attempt of mine, but I don't have any knowledge of this aspect.

Its a Perl programme that, as a user, I can only run from an Entry Information Page. It shows the visible page, not the underlying code.
[Edith Daisy Dent.pdf](https://github.com/FreeUKGen/FreeBMD2/files/7418754/Edith.Daisy.Dent.pdf)

**Comment by PhilipClarke712** [comment] 2021-10-27 08:03
@PatReynolds ,

I don't know what is intended for FreeBMD(2) Phase 5+, but the system in operation in FreeBMD(1) does not appear in my view to be fully implemented in respect of communications to 'correctors' of pending requests nor give user feedback on "closed" requests:
(1) As a researcher, when I submit a data-change request, if I tick the box, I receive an email that my request has gone in and will be considered and possibly a change will  **appear** in the next one or two months (two up-date cycles). I've never ever been notified whether any request was excepted, rejected or partially implemented (as someone to does corrections on my transcriptions that is the information that I submit back to the system when I "close" a request). I can of course repeat the search at a late date and find out for myself if my change was processed.
(2) I transcribe for two syndicates, one chooses (that is a syndicate choice) to do their corrections in bulk, but they let me do my own); the other syndicate choose to allow active users to do their own corrections. The requests system should notify either the syndicate or the user that a request has been raised. I believe that I can correctly state that we are not notified. We have to look, either at our syndicate or own requests application; or at the daily statistics.

I don't know how system change requests are managed on FreeBMD(1), but it might be worth checking whether there is an outstanding request to implement notifications.

**Comment by richpomfret** [comment] 2021-11-08 17:21
@PatReynolds to ask Allan about where the 'ticket' should go.

**Comment by PatReynolds** [comment] 2021-12-06 12:50
Asked 6/12/2021

**Comment by DeniseColbert** [comment] 2021-12-20 17:30
@PatReynolds to ask Allan again

**Comment by PatReynolds** [comment] 2022-01-10 12:01
The correction request goes to the transcriber (or if they are not able / willing to correct, to the syndicate coord (see https://www.freebmd.org.uk/CorrectionsProcess.html).

**Comment by PatReynolds** [comment] 2022-01-10 17:30
@PatReynolds to check with project that this is this still the case

**Comment by PatReynolds** [comment] 2022-01-24 11:27
Asked correctionscoord@freebmd to check process.

**Comment by PatReynolds** [comment] 2022-01-25 17:09
@Vino-S please see email from Barrie forwarded today (25 Jan 2022)

**Comment by PatReynolds** [comment] 2022-03-21 17:20
@Vino-S to set up a mail system for BETA - to go to DATA -Cord role role.

**Comment by DeniseColbert** [comment] 2022-09-05 16:50
@PatReynolds to send Barrie's email to Denise, and we'll then work out where the messages will go.

**Comment by DeniseColbert** [comment] 2023-01-10 15:57
@PatReynolds @PatReynoldsFUG could you please forward Barrie's email (mentioned above)?

**Comment by Vino-S** [comment] 2023-02-07 14:33
Ready for testing in test3

**Comment by DeniseColbert** [comment] 2023-02-07 15:03
@DeniseColbert to reprt a data problem and check that it makes it into Contacts

**Comment by DeniseColbert** [comment] 2023-02-21 15:09
Tested; works fine

**Comment by DeniseColbert** [comment] 2023-02-21 15:10
Still needs Barrie's email from Pat

**Closed as completed** 2023-03-07 15:03 UTC
Labels: documentation, MVP, ready for deployment, Phase 3 - for initial user research
