### ISSUE TITLE
Check the searching of districts that cross the English Welsh border with full database

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#377] opened 2021-07-19 16:58 UTC
Some districts England/Wales are cross-border - see e.g. https://www.ukbmd.org.uk/reg/districts/chepstow.html (Chepstow) includes Alvington and Aylburton (both Gloucestershire) and Caerwent and Caldicot (both Monmouthshire) to take just the first four subdistricts.

In the case of William Robert Smith, baptised in Chepstow in 1854 (https://www.freereg.org.uk/search_records/5f932ccef493fd032b89c120/william-robert-smith-baptism-monmouthshire-chepstow-1854-09-14?locale=en)
On FreeBMD1 a search of Gloucestershire reveals him in the Chepstow district, and a search of Monmouthshire reveals him in the Chepstow district. Chepstow town is in Monmouthshire.
On FreeBMD2 he is found searching Monmouthshire, but not searching Gloucestershire.

This needs checking after FreeBMD2 is using the full database, and guidance for users provided

**Comment by richardofsussex** [comment] 2023-08-11 15:20
Again, I would like clarification as to what the actual task is here. Is this issue about [Registration] Districts which span county boundaries?  If so, what do we actually want to do about them? I don't see why crossing a national border makes any difference to the issue (whatever it is), since there is no filtering by country, and "England and Wales" are seen as one 'thing' in the drop-down list of counties.

**Comment by DeniseColbert** [comment] 2023-08-14 15:51
Vino will look at this to see if this is caused by the different search logic between BMD1 and BMD2

**Comment by richardofsussex** [comment] 2023-08-22 15:28
Please check whether this issue applies across all counties, not just those spanning the border between England and Wales. I suspect that it does!

**Comment by KristinaGadzhieva** [comment] 2023-12-12 15:26
@Vino-S Please have a look

**Comment by Vino-S** [comment] 2024-01-09 10:37
On testing in complete database, this issue no longer exists

**Comment by Vino-S** [comment] 2024-01-09 10:37
On testing in complete database, this issue no longer exists

**Comment by DeniseColbert** [comment] 2024-01-09 15:26
Closing as no issue in Beta (complete database)

**Closed as completed by DeniseColbert** 2024-01-09 15:26 UTC
Labels: MVP, Phase 4 MVP Release, Search page
