### ISSUE TITLE
Help: finding a spouse

### ISSUE THREAD

**Issue by richardofsussex** [FreeUKGen/FreeBMD2#516] opened 2022-09-20 14:59 UTC
The help section on "How to find the name of a spouse" describes how to run a search to retrieve all the entries on the relevant page. Surely, all you need to do is to view the detailed record, and then click on the page number, which is a link to exactly that information?

**Comment by AlOneill** [comment] 2022-09-23 22:10
Advice amended at https://test3.freebmd.org.uk/cms/help/draft-help#findSpouse
Other issues addressed on this draft: #447 and #506

**Comment by PhilipClarke712** [comment] 2022-09-27 06:19
richardofsussex's question / suggestion would provide an quick answer on BMD2  **if** there was near 100% coverage **and** there was "good clean data". 

Clicking on the page number (but we 'select' rather than 'click') would run the search again - but what is it searching? (a page number is non-unique) - it's repeating the search using the same timeframe (a quarter or year - which is GRO index-dependant), page number and volume number, (plus District if specified - but you can order a certificate without giving the district). 

The search may fail if there is less than full coverage or there is "unclean data" - for example the transcriber may have put quarter three in the file header instead of quarter two; and the other partner is to be found at quarter two, on the same page number - but they will not match. On BMD1 that transcription could - if it fails quality checks - be flagged as Confirmed-false and the entry would be 'flagged up' in italics, but not on BMD2. One spouse's page number may have been 'correctly transcribed as 166' and the other as 116, or perhaps [1_][68_]6. On BMD1, but not BMD2 that page number 116 might be flaggged - if it failed quality checks - as Confirmed-false and flagged as such in italics. 

Some of these problems could be identified on BMD2 if we suggested that the researcher views the image of the GRO index page and confirms (or not) that the GRO index matches what the computer shows.

I'm not too sure that just two 'hits' is sufficient on pre-1912 records. One of the "problems" that Michael Foster showed was that the vicar, or his assistant (illegally) pre-filled in the the marriage entry before the service and wrote down one surname as say Matthews, but the signature was Mathews. That could result in two separate GRO Index entries with the same page number for one spouse - that would also be true for post 1911 entries giving rise to four entries Matthews - Smith; Smith - Matthews; Mathews - Smith; and Matthews - Smith. This is fairly obvious, but would Smyth and Smith be so obvious? I have cousins that have married, one hundred years or so ago, with the same Surname. But a bride might have been so overwelmed in the service that she signed using her new married surname and rather than her maiden name. So is a Hayes - Hayes marriage one complete marrriage; a possible brother and sister that married at the same time (but not to each other); or two unrelated spouses (with as yet unknown spouses).

The pre-1912 indexes can't answer those "questions" - you need the certificate, or it might be on FreeReg.

Certainly an odd number of entries would suggest that one entry is missing, or that perhaps one entry has a transcription / indexing error - but which one? (the Index does not help for pre-1912 indexes).

BMD1 has a more detailed help page - https://www.freebmd.org.uk/marriage-help.html . Well so does FreeBMD2, at least in draft and a story to go with it #132 opened in Aug 2019, Phase 4 MVP release. It was sent for review on 5th Feb 2021 and has been on Ice since.

**Comment by richardofsussex** [comment] 2022-09-27 09:07
@AlOneill has addressed my initial concern, as noted above. Picking up on the points that @PhilipClarke712 makes, there is one aspect which we _do_ have control over, which is the flagging up of data which we ourselves are unsure about. As he says, this is done in BMD1 but not in BMD2. If we want to implement this (and the associated emboldening of double-keyed entries, which I think also hasn't been implemented), please raise a new issue and assign it to me.

**Comment by PhilipClarke712** [comment] 2022-09-27 13:19
Hi @richardofsussex I got into a sort of cross-communication-miss-understanding with Barry a year or more ago over the use of "Confirmed" in conjunction with the BMD2 test-database. He was using 'it' as data field (presumably a binary-value <true or false> generated during the QA cross-checking of page number/volume number/district name combinations for each record against statistical-generated confidence levels, every time the BMD database has its 28-day update) [I hope that says what I'm trying to say]. I was speculating that the test database was not the latest version, and it was possibly up to eight-years old. "Confirmation" to me was just a 'word' meaning that Pat said it was an older database (but not how old it was). I as a potential Research user of BMD2 I would like to see both of those implemented. If the BMD database has a flag against every record, implementation just means making that flag visible somehow in the Search results when it is "false".   I could open a new story on Github, I have done that before. However, doing so and assigning it to you seems to be above my 'pay-grade' - I don't get paid. I'm committing resources, unless someone over-rides me.

**Comment by DeniseColbert** [comment] 2022-10-18 14:42
@AlOneill to check draft and make sync ready

**Comment by AlOneill** [comment] 2022-10-18 17:39
Help is now sync-ready.

It also contains the definitive details of [how to order a certificate](https://test3.freebmd.org.uk/cms/help#orderCertificate)

**Comment by DeniseColbert** [comment] 2022-11-01 15:09
This needs syncing to @Vino-S

**Comment by DeniseColbert** [comment] 2022-11-15 15:32
Content should be there, images missing but Vino to talk to lemon about that

**Comment by DeniseColbert** [comment] 2022-12-13 15:15
@AlOneill please test this after lemon's fix

**Comment by DeniseColbert** [comment] 2023-01-10 15:19
@Vino-S is this ready for @AlOneill to test?

**Comment by DeniseColbert** [comment] 2023-01-24 15:18
Deployed so closing

**Closed as completed by DeniseColbert** 2023-01-24 15:18 UTC
Labels: ready for deployment
