### ISSUE TITLE
Display postems on Entry Information page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#164] opened 2019-11-02 12:09 UTC

**Comment by archerbarrie** [comment] 2019-12-16 12:07
Firstly, I don't like the use of "detailed results page". Unlike FreeREG (and I assume FreeCEN) there is normally no further detail here compared with the search results, although you do get to see all the transcriptions that made up the entry. I think "Information Page" is much more neutral.

Secondly, what is the alternative? Postems are currently shown on the Information in FreeBMD1 so this is effectively "no change" which I thought would be the default. Or at least this should be part of a description of what is on the FreeBMD2 information page rather than being a separate topic.

**Comment by PatReynolds** [comment] 2020-02-17 16:22
@archerbarrie the 'detailed results page' is just a name (the common name across projects). Here it means the page that equates to the FreeBMD1 Entry Information page.  So yes, this is part of the description of what is on the page.

**Comment by archerbarrie** [comment] 2020-02-17 17:54
@PatReynolds The title of a page is __NOT__ "just a name", of course it isn't, it conveys meaning and generates expectation. I understand that the other projects use "Detailed results page" but my point was that the name was appropriate for those projects but not for FreeBMD. One could have a debate about balancing consistency against meaningfulness, but that is a debate that is lacking.

**Comment by PatReynolds** [comment] 2020-02-17 18:06
You make good points, @archerbarrie I will start a new issue so they can be discussed.

**Comment by Captainkirkdawson** [comment] 2020-02-17 20:17
I only partially agree with @archerbarrie on his statement. What he says is true for FreeBMD.
But it does NOT need to be for FreeBMD2. 
It was my understanding that we wished to restructure and redisplay fields where appropriate within BMD2. Hence if that is indeed done detailed result page might well be appropriate terminology for BMD2. 
Unless of course the whole purpose of for BMD2 is to simply replicate BMD1 in its current form with only minor tweaking.

**Comment by PatReynolds** [comment] 2020-02-18 13:08
This is (currently) essentially 'no change' (i.e. a link is displayed).

However, we could show the postems, rather than a link.  Since 'postem' is not a transparent term, showing might be better, and fewer clicks is usually considered better.

**Comment by archerbarrie** [comment] 2020-02-18 16:40
@PatReynolds  What does 'no change' mean? No change from what? Apparently no change from a link being displayed but where does that happen? Not in FreeBMD1 where the Postem is shown on the Information page (without any click).

**Comment by archerbarrie** [comment] 2020-02-18 16:50
@Captainkirkdawson I find it somewhat bemusing that we don't appear to be sure what the objective of FreeBMD2 actually is. Originally it was supposed to be a reskinning but things seemed to have moved away from that to, in my opinion, something of a let's reinvent the wheel. Personally I would have thought that the baseline would be a reskinning (to gain acceptance from current users) but with deviations where these can be justified. However, I have seen little to indicate this is what is happening, particularly little in the way of such justifications. But that is all just my view, looking on from outside without really understanding the development process.

**Comment by PatReynolds** [comment] 2020-02-19 11:57
My mistake, @Barrie - I couldn't recall the specifics of a record to check.  So definitely we would want to show rather than provide a link .

**Comment by KatyMawhood** [comment] 2020-04-28 10:28
@PatReynolds Could you give/link an example of the postems to be displayed on the detailed results page?

**Comment by archerbarrie** [comment] 2020-04-28 11:11
@KatyMawhood Postems can be viewed at https://www.freebmd.org.uk/special-cgi/ShowPostems.pl. Tick "7 days" and then Find to see the most recently added. An example of how a postem is displayed currently is
![image](https://user-images.githubusercontent.com/14543258/80480793-300d0900-8949-11ea-83d2-4855baecbdb8.png)

**Comment by KatyMawhood** [comment] 2020-04-28 13:02
Thanks @archerbarrie – this is really clear. 

Can a user register/login at any time to create a postem? Or is the option only accessible to transcribers as they work on each entry?

**Comment by archerbarrie** [comment] 2020-04-28 14:19
@KatyMawhood No, it's the opposite to that. Transcribers cannot add postems, only users (researchers) and they don't need to login (but they do need to get past a CAPTCHA). On the information page there is 
![image](https://user-images.githubusercontent.com/14543258/80494549-ac5e1700-895e-11ea-8bc4-84f5b3c15f4d.png)
and clicking on add a postem takes you to the Create a Postem page (which has the CAPTCHA).


Now, transcribers __can__ add comments (which are either #COMMENT or #THEORY) and look like this
![image](https://user-images.githubusercontent.com/14543258/80495657-1c20d180-8960-11ea-8e51-f304a1377a3e.png)
and here the transcriber is opining that the surname should be Whitehaven (for some unknown reason).

**Comment by KatyMawhood** [comment] 2020-04-28 15:15
@archerbarrie Thanks Barrie, I'm glad I asked! 

Re: viewing – I can't currently access the BMD [Show postem](https://www.freebmd.org.uk/special-cgi/ShowPostems.pl) link because it's protected by a username and password. @PatReynolds suggested that you may be able to help with that?

**Comment by archerbarrie** [comment] 2020-04-28 15:20
@KatyMawhood Sorry, I gave you the wrong link. The one I gave you is an admin version for managing the Postems, the one you need to view them is  https://www.freebmd.org.uk/cgi/ShowPostems.pl

**Comment by PatReynolds** [comment] 2020-08-11 11:12
'Postems' is an obscure term.  I think the label should be 'More about this record from other users (Postems).'

I think we may need a separate 'add what you know' button as the text will be too long for the button if it is all in one. Help note 'please use this link to add what you know about the people or event in this record'

**Comment by PatReynolds** [comment] 2020-08-12 16:05
@PatReynolds to test

**Comment by PatReynolds** [comment] 2020-10-21 09:58
Link from search results to Entry Information page is not working on either test2 or test3 - @Vino-S could you take a look?

**Comment by Vino-S** [comment] 2020-10-21 10:15
Hi @PatReynolds , the links seem to be working. Could you check it once again, please?

**Comment by PatReynolds** [comment] 2020-10-21 15:59
Thanks, working fine now @Vino-S

**Comment by PatReynolds** [comment] 2020-10-21 16:03
If a Postem exists, it asks you to leave a postem.
If a Postem does not exist, it shows nothing.

**Comment by richpomfret** [comment] 2020-10-21 16:15
@Vino-S to update TEST3 with latest code.

**Comment by Vino-S** [comment] 2020-11-18 16:41
Ready to be tested on test2

**Comment by PatReynolds** [comment] 2020-11-26 09:27
Working - 
![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/a0e9c234-f8a0-4a03-940c-abb7b91a4e0b)

**Comment by archerbarrie** [comment] 2020-11-26 10:02
It is difficult to be sure but it looks like the display has failed to convert the link into a clickable link (see below). I could not test this because I could not find the record in 1870B4 (which is where it is).
![image](https://user-images.githubusercontent.com/14543258/100336720-6b9aaf00-2fce-11eb-9237-3751b8a5573e.png)

**Comment by PhilipClarke712** [comment] 2020-11-26 10:19
Hi Barry, 

It is on FreeBMD, I looked out of curiosity and  I've just found it: 

Births Dec 1870 : Austin, Agnes Augusta, Kettering, 3b, 161, 

![Agnes Augusta Austin](https://user-images.githubusercontent.com/67054943/100338564-a56cb500-2fd0-11eb-8071-8091956f6c27.png)

**Comment by archerbarrie** [comment] 2020-11-26 10:27
Yes it is but it is not on the test site. Also it was added to the live site at 09:32 on 26/11/2020, that is after Pat's comment that quoted it as being on the test site. I do hope I am wrong but there is a worry here that the test site is modifying the live database.

**Comment by PatReynolds** [comment] 2020-11-26 10:39
I added it to the live (freebmd1 site).  It's a genuine postem.  I was testing this to make sure that there wasn't another step after the Captcha that I wasn't aware of (e.g. moderation) that we had to put in to FreeBMD2.

It's nice that FreeBMD1 makes it a live link, and I think we should implement that in FreeBMD2, too. 

[Not nice is the Monetizemore Advert that intervenes itself - noticed this somewhere else on FreeBMD this morning, will ask that they stop it]

**Comment by archerbarrie** [comment] 2020-11-26 11:09
That's a relief! I was hoping that was the answer. But I still don't understand why I could not find the record on the test site.

**Comment by PatReynolds** [comment] 2020-12-03 12:20
tested on FreeBMD2 @Vino-S could you make the url clickable?

**Comment by PhilipClarke712** [comment] 2020-12-03 13:31
As Pat's comment, immediately above, dropped into my mail box very recently I looked for the **Agnes Augusta Austin** birth-postem on both test2 and test3 and I found both postems (25th & 26th Nov) on test2 and test3: I'm pleased to say.

Earlier in this thread Barry showed a marriage-postem for **Lawrence W A Aldridge**: it was for the 1934 marriage. Lawrence married twice and FreeBMD(1) has a postem for both marriages (he married again in 1942).

I found his two marriage records on both test2 and test3. Neither of his marriages have postems attached, but both test2 and test3 would allow me to add postems. On test3  I added a blank postem (its dated 2020-12-03) for the 1942 marriage.

I don't know how FreeBMD2 handles postems: but from a black-box view point, it does not seem to find, or perhaps display, these two postems that are on the FreeBMD(1) database.

**Comment by PhilipClarke712** [comment] 2020-12-03 13:33
Sorry, I click on the wrong butten

**Comment by PatReynolds** [comment] 2020-12-03 16:13
Thanks, @PhilipClarke712 I will raise this as a new story as I don't think that is necessary for the initial testing which is at the end of phase 3, and which we hope will be within the next few weeks.

**Comment by archerbarrie** [comment] 2020-12-03 22:02
> 
> 
> As Pat's comment, immediately above, dropped into my mail box very recently I looked for the **Agnes Augusta Austin** birth-postem on both test2 and test3 and I found both postems (25th & 26th Nov) on test2 and test3: I'm pleased to say.
> 
> Earlier in this thread Barry showed a marriage-postem for **Lawrence W A Aldridge**: it was for the 1934 marriage. Lawrence married twice and FreeBMD(1) has a postem for both marriages (he married again in 1942).
> 
> I found his two marriage records on both test2 and test3. Neither of his marriages have postems attached, but both test2 and test3 would allow me to add postems. On test3 I added a blank postem (its dated 2020-12-03) for the 1942 marriage.
> 
> I don't know how FreeBMD2 handles postems: but from a black-box view point, it does not seem to find, or perhaps display, these two postems that are on the FreeBMD(1) database.

@PhilipClarke712 I believe that the test2 and test3 databases are snapshots of the live database at some point in time (and are possibly the same snapshot). The Postems in question were added 21/04/2020 so the implication is that the snapshots were taken before that time. I cannot check that because whenever I try test2 or test3, all searches produce no results.

**Comment by PhilipClarke712** [comment] 2020-12-04 00:07
Thanks for that Barrie. I have no knowledge of the underlying FreeBMD(1) database / search engines, which is why I was treating it as a "black box" system (if I had that knowledge it would be a "white box" or a "glass box" system).

Most of the 1934 marriages (looking at the graphs on FreeBMD) were loaded onto the FreeBMD system between the autumn of 2008 and the end of 2009; and 1942 marriages were also mostly loaded in 2010. So, the snapshot of the database can't be older than the end of 2009 and probably post-2010. 

Just now, I searched FreeBMD for a postem created in January 2015 and the one I took was a 1897 Wigan R.D. Marriage of **Harriet Ann Harris**, she is on test3, but she has "no" Postem. I then found a FreeBMD postem for a December 1909 marriage of **Mary Moore**, in Shardlow R.D. : her postem was loaded 1 Jan 2010; and the marriages were loaded in 2004. Test3 has her record but does not "see", or "have", her postem. These are only two records, so not all that significant for the hundreds of millions of records.

Presummably, it comes down to one of two things, the snapshot of the live data base does not include postems, or the parameters employed in the search engine don't return with the FreeBMD(1) postem data. However, it returns postems that have been recently created on test2 / test3. So could the FreeBMD(1) postems and the test 2 / test 3 generated Postems "look different" to the search engine. 

This is way out of my area of knowledge.

**Comment by archerbarrie** [comment] 2020-12-04 01:41
Well, it looks like my assumption about FreeBMD2 using a snapshot may be incorrect. For some reason the test database on vervet contains very few Postems, just 15, all of them tests, e.g. Deaths 1856 Jun Bainbridge,Joseph. I cannot tell if this Postem is on test2/3 because cgi/ShowPostems.pl crashes on test2/3 but if they do contain this postem it would seem that test2/3 are using the test database. The live database contains over 400,000 Postems as does the database in my development area.

**Comment by PhilipClarke712** [comment] 2020-12-04 08:16
Thanks Barry.
It took me some time to find that record on test 2/3.
On FreeBMD: the record is BAINBRIDGE, Joseph Hall, Kensington, 1a, 25 and there are two postems dated 10th and 18th of April 2015. They read: 
(1) Joseph Hall BAINBRIDGE age 31 (See: http://www.gravestonephotos.com/volunteers/private/cemeterylist.php?cemetery=2452&country=En&limit=&scrwidth=1093)
 (2) Joseph Hall BAINBRIDGE age 30 baptised 1825 Madras India d: 19 May 1856. Son of Joseph BAINBRIDGE & his wife Elizabeth Sarah née RICHARDSON.

It's a "double-keyed" record with three different transcribers.

On test2/3, I ended up searching for a death of Joseph Bainbridge, in the range 1856 to 1860 with a Volume of 1a and came up with:
JOSEPH _ BALL BAINBRIDGE
he has two postems:
(1)  2015-04-18 , Thisisaverylongpostemtotestthatbrowserscansuccessfullynowhandleverylonglinesthatusershaveinthepastleftwithoutanyspacessothattheycanmaximisethenumberofcharacterstheycangetinapostem
(2)  2015-04-19 , Submitted by: Test for escape

Test 2/3 does not currently name the transcribers, not indicate whether a record is single-keyed or double-keyed.

The keying dates for 1895 death records are at https://www.freebmd.org.uk/statgraphs/deaths-1856.gif . Only the first two keyings pre-date 2015 (when the postems were added). So, test 2/3 could be using a pre-Apri-2015 version of the data base, which would not have the real FreeBMD postems.

This seems to generate more questions than answers.

**Comment by PatReynolds** [comment] 2021-01-13 17:41
Hi @PhilipClarke712 

Yes, this is an early database.

The multiple transcriptions / transcribers is indicated on the Entry Information Page.

So this is working ok?

**Comment by PhilipClarke712** [comment] 2021-01-13 18:02
Hi Pat,
I was looking for Postems and, you have confirmed that it is an earlier data-base. The fact that it is a early data-base means it has almost no postems. 
The _problem_ is the data-set: that data-set is not the one that I (or we) would choose to use to test the  Postem search capability. However: since I'm told there are just 15, I'll change my search strategy to looking for what is know is there.

**Comment by archerbarrie** [comment] 2021-01-14 19:34
> The multiple transcriptions / transcribers is indicated on the Entry Information Page.

And how is "confirmed" (as indicated by Confirmed & 1 in the database being non-zero) indicated? This is the question that was implied originally.

**Comment by PatReynolds** [comment] 2021-01-15 11:15
@archerbarrie if the  'confirmed' in Philip's comment of  13 Jan 2020 is the one you mean, 'confirmed' means 'Pat says, yes,  it is  it is an earlier database.  

Not sure what yo mean as I don't think your comment refers to that.

**Comment by PhilipClarke712** [comment] 2021-01-15 13:00
@PatReynolds,

Sorry, I did not reply to the second part of your question above and that is the topic of the first line of Barrie's comment, above.

The second part is going somewhat off the topic of Postems, but I'll respond here: I could do searches on the 13th (I was using test3) but when I clicked on the View button the system was timing out with a 404 error. My internet went down for several hours last night: so the problem might have been on my ISP's servers. I have repeated the search just now.

Test2 and test3 work slightly differently: test2 does name the transcriber(s), but test3 does not. So, I'll just respond in respect of test2 searches, versus FreeBMD.

If I do a blanket birth search for (forenames) **Joseph Hamer** (surname) **Smith** I get two "hits": a September 1838 birth with two named transcribers (on test2) and a September 1884 birth with one named transcriber (on test2). If I do the same search on FreeBMD I get the same result: but the whole of the line of the 1838 entry is bolded (so is flagged up as double-keyed) and the whole of the line of the 1884 entry is not bolded. I like the fact that FreeBMD uses symbols, bolding and italics to flag something that might be of interest to me. On test2 I get a table of result (two) for this search. The 1838 surname SMITH might be (?) bolded, whereas the 1848 Smith is not bolded. It is also possible that the full name of both results are bolded versus the text used for the date and the record type (Birth). As a result, I failed to see the bolding (as in use on FreeBMD), or failed to recognised the significance of the surname-name case. 

I think there are two shades for grey in use (FreeBMD2 uses grey rather than black and white). Could I have the day-glow-orange version, in black or grey, for double-keyed records? I don't think the contrast between Smith (single-keyed) and SMITH (double-keyed) is **blindingly obvious** (sorry about those last two words).

**Comment by archerbarrie** [comment] 2021-01-15 13:05
> @archerbarrie if the 'confirmed' in Philip's comment of 13 Jan 2020 is the one you mean, 'confirmed' means 'Pat says, yes, it is it is an earlier database.
> 
> Not sure what yo mean as I don't think your comment refers to that.

No it doesn't. "Confirmed" means that an entry has been confirmed by double keying. This is indicated by a flag on the entry in the database and, in FreeBMD1, by the entry being in bold. So the question is "how is the entry being  in bold in FreeBMD1 indicated in FreeBMD2"?

**Comment by PatReynolds** [comment] 2021-01-15 14:59
Thanks, Barrie, different story. #271 (in backlog, so no resolution yet on confirmation with that meaning.

**Comment by Vino-S** [comment] 2021-02-10 15:22
Code deployed to test3. So closing it

**Closed by Vino-S** 2021-02-10 15:22 UTC
Labels: ready for deployment, user experience
