### ISSUE TITLE
Implementation of the Search Page

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#82] opened 2019-06-17 14:26 UTC

**Comment by Captainkirkdawson** [comment] 2019-06-27 20:25
Current wireframe is https://drive.google.com/open?id=1omxtCfNVypHN9wL0QXgZb2JjChOyWKjS

**Comment by PatReynolds** [comment] 2019-07-08 17:13
ToDo on the footer (the red, white and black panels at the bottom of each page).
a) change text in red part to reflect FreeBMD and requirements of the GRO.
b) Add extra social media (etc.) icons, group to right with 'Follow us' above (as on wireframe)
https://drive.google.com/file/d/1omxtCfNVypHN9wL0QXgZb2JjChOyWKjS/view
c) Add second column of links i.e. News, Help, [more text to follow]

**Comment by Captainkirkdawson** [comment] 2019-09-02 22:36
Comments on the search form itself have not been requested but a couple of early observations.
1. The record type selection box takes too much space
2. I like the placement of the spouse boxes above the location boxes. 
3. Could we not get the clear and search buttons on the same lane as the location boxes?

**Comment by AlOneill** [comment] 2019-09-03 00:06
It may be too early but …

Tabbing through the form is broken, in two different ways, in both Chrome and Firefox. I believe this to be caused by the mixed use of `tabindex="0"`, `tabindex="n"`, or nothing — different browsers have very different rules for how to implement such a mixture.

The only safe approach is to have **all labels and form controls that a user needs to access set to `tabindex="0"`** and to **adjust the source order to match the desired tabbing order** — which could be tricky.

**Comment by DeniseColbert** [comment] 2019-09-30 15:33
Search parameters: Denise Colbert; Birth; 1954 - 1991.

FreeBMD1: 
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/79463de2-0f66-4068-b155-ee5bff50bc6f)

FreeBMD2:
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/2c145d1b-447a-4b6c-80d0-0bae5ff588ef)

Issues:
* FreeBMD2 search doesn't find 1954 entry
* Quarter number seems to conflate the quarter and the year (so Q4 1978 becomes 478)

**Comment by Vino-S** [comment] 2019-10-04 00:05
@DeniseColbert , 
Issues:

1, FreeBMD2 search doesn't find 1956 entry

FreeBMD1 test website also gives one record below is the link
https://test1.freebmd.org.uk/cgi/search.pl

I suppose you might have used the live FreeBMD1 website, which uses different database, so there is a possibility that we get different list of results. 

2.  Quarter number seems to conflate the quarter and the year (so Q4 1978 becomes 478)

The Quarter number 478 will be changed to Year and Month after further coding. I kept the Quarter Number column for my reference. I will change it to Year and Month in my next code update.

**Comment by richpomfret** [comment] 2019-11-25 17:55
We need to refine this story down for it to have a specific meaning - it's otherwise a bit vague.

**Comment by PatReynolds** [comment] 2020-01-13 17:14
Tab ordering is broken, and differently broken in different browsers (comment from @AlOneill )

@AlOneill to comment further

See also @Captainkirkdawson s comment on #185

Others to review their previous comments and sign off.

**Comment by richpomfret** [comment] 2020-02-25 17:40
Tab ordering fixed and ready for testing! @PatReynolds and @AlOneill  to take a look.

**Comment by AlOneill** [comment] 2020-03-02 15:28
Tab order fine, thank you.

However, a number of accessibility issues remain: focus is not visible on some items; when Enter is used on labels/info links (as a keyboard-only user would have to do), in addition to the i-frame opening on the search page, the "Help" page opens in a new tab, without warning and at the top rather than at the pertinent point (for some items at least — did not check them all — I ended up with half a dozen "Help" page tabs).

Once in the i-frame, it is not clear to me how a keyboard-only user would get out of the i-frame and back onto the Search page proper. It seems that we need short bits of info text that can be shown accessibly on the Search page.

**Comment by Vino-S** [comment] 2020-03-03 14:00
I agree with Alison,
I will remove the iframe from the search form and go with plain short help text. As suggested by Alison

**Comment by Vino-S** [comment] 2020-03-24 16:43
Done. Its in test2 for testing

**Comment by Captainkirkdawson** [comment] 2020-04-07 14:44
Seems OK from my knowledge of accessibility.

**Comment by AlOneill** [comment] 2020-04-08 17:50
@PatReynolds @Vino-S Good improvements, TY, but there are still some issues for keyboard-only users:
* Messages to "click on the label" are flawed — hitting enter has no effect
* On a wide screen, the tool-tips in the second row do not show in full — they are too long, with the exception of: "Spouse's first name" (OK); "Spouse/Mother surname" and "Age at death" both appear to have no content (first does not accept focus, second shows as empty (or misaligned?)

Many of the tool-tips contain full-stops with no space before the next sentence.

No visible focus on "Clear form" or "Search".

NB this may not be a complete list of issues: I have run out of steam!

**Comment by Vino-S** [comment] 2020-05-19 15:58
Fixed the tooltips. 
Working on Search Button. Will fix it while working on issue #184

**Comment by DeniseColbert** [comment] 2020-07-15 16:08
Responsiveness of the navigation bar needs to be tested

**Comment by Vino-S** [comment] 2020-07-15 16:10
the code is updated in test3

**Comment by AlOneill** [comment] 2020-07-17 14:13
The navigation is not responsive in that below a screen width of about 1050px, the main menu is replaced by a hamburger icon that does not do anything.

Also, the contents of the 'Age at death' tooltip could be better: Optional. Age can also be entered Number(range) or Date of Birth(range)
Perhaps there should be 'as a' between 'entered' and 'Number', and also between 'or' and 'Date'? There is probably a better way of phrasing the tooltip … will think on.

There should be a space between 'Number' and '(range)' and also between 'Birth' and '(range)'. How do people enter a range? Two values separated by a hyphen? Two years for the Date of Birth, separated by a hyphen?

For the Record Type tooltip, there is a phrasing issue: Specify whether you are searching for Births, Marriages or Death records. If no checkboxes are checked means all the three types.

How about: Choose to search for Birth, Marriage or Death records. If no checkboxes are checked, the search will look for all 3 types.

The Search button has visible focus, TY, but Clear Form still does not.

**Comment by PatReynolds** [comment] 2020-07-28 16:29
@AlOneill can you let @Vino-S know what she needs to do to give Clear Form visible focus?

@Vino-S to fix hamburger on mobile once we have a mobile layout.

@Vino-s to make changes to tooltips /info buttons

**Comment by AlOneill** [comment] 2020-07-29 16:31
@Vino-S I would simply add `.clear_form:focus` as a selector to `.clear_form:hover`, which is defined in freebmd_content.css

**Comment by Vino-S** [comment] 2020-07-30 09:47
Thanks @AlOneill, will do it

**Comment by Vino-S** [comment] 2021-02-10 13:29
Deployed to test3. So Closing it.

**Closed by Vino-S** 2021-02-10 13:29 UTC
Labels: Developer, beta testing, ready for deployment
