### ISSUE TITLE
Researcher can download results in FreeBMD1 format

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#103] opened 2019-07-22 11:57 UTC
The format needs to be consistent as researchers have written personal programmes to hold/manipulate search results page data.
 See https://drive.google.com/file/d/1AWUbDuxKgW5tARORasV09r2XLvuRTMER/view?usp=sharing) for example.

Textual portions can change, it is the table of entries, and key, that need to be replicated.

**Comment by Captainkirkdawson** [comment] 2019-07-22 14:41
Is this to part of MVP?

**Comment by richpomfret** [comment] 2019-07-22 15:41
For MVP we use FreeBMD1 approach - we can look at anything further post-MVP.

**Comment by richardofsussex** [comment] 2022-10-10 19:00
I'm happy to have a look at this issue.

**Comment by richardofsussex** [comment] 2022-10-10 19:36
The CSV output currently offered in test3 is close to what is required. I suggest that we reorder the columns to match the BMD1 order, add the AAD/Spouse/Mother and Flags columns, and possibly tweak the format of the Event and Quarter columns so they match the BMD1 format. Also, the CSV separator needs to be tab, not comma.

**Comment by richardofsussex** [comment] 2022-10-11 13:45
OK: I've made an implementation of issue 102. Modified the existing "download as CSV" option so that the result is compatible with BMD1 'download' format: tab-separated output; same headings/data in same order. Also aligned output to the currently selected sort order.

One observation is that the sorting of districts has reverted to the previous incorrect behaviour: I had to change a DistrictName assignment before it would run, so that might be the cause. Or else the freebmd_development branch doesn't contain the fix for district sorting.

We might want to think about limiting the number of records which can be output in this way. Users can only view up to 100 records at a time, but "download as CSV" outputs the entire search result, i.e. up to 3,000 records. One strategy would be to have the CSV download match what they can see on the screen, i.e. 100 records max.

**Comment by DeniseColbert** [comment] 2022-11-01 15:43
@Vino-S to push to test3

**Comment by DeniseColbert** [comment] 2022-11-15 15:28
@DeniseColbert to test

**Comment by DeniseColbert** [comment] 2022-11-29 12:00
Looks good! I agree about download limiting to what is viewable

**Comment by DeniseColbert** [comment] 2022-11-29 12:09
To check policy with trustees

**Comment by DeniseColbert** [comment] 2022-11-29 13:49
@Vino-S could you look into paragraph 2 of Richard's above comment please? seem to have missed that in Scrum.

**Comment by DeniseColbert** [comment] 2022-12-13 15:46
@Vino-S to look at the potential merging issues

**Comment by DeniseColbert** [comment] 2023-01-10 15:50
@Vino-S now assigned

**Comment by DeniseColbert** [comment] 2023-01-24 15:32
Changes are merged in main branch (FreeBMD master) in Beta

**Comment by DeniseColbert** [comment] 2023-02-07 15:35
Done, closing

**Closed by DeniseColbert** 2023-02-07 15:35 UTC
Labels: MVP, Phase 3 - for initial user research
