### ISSUE TITLE
Implementation of save search feature

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeBMD2#123] opened 2019-08-12 13:49 UTC
Save search feature as member feature. To discuss exact design/requirements for this and what we might provide (time allowing) for MVP..

Pat to discuss with FreeBMD team.

**Comment by PatReynolds** [comment] 2020-03-02 10:52
@Barrie, what are the design requirements for this, please?  I'll ask the Documentation Team for their perspective, as users, too.

**Comment by PatReynolds** [comment] 2020-03-24 11:46
Documentation team reported not using this feature.  Those who tried it, were expecting a download of search results, as with FreeREG/FreeCEN.  this feature (printable format) already exists in FreeBMD2.

Suggest move to post-MVP for implementation.

**Comment by PatReynolds** [comment] 2020-04-07 17:05
Multi modal saves search results in an array, so will differ when changes to the database mean a different set of records are found by a search.

The resaercher therefore can compare the search at a previouis date (saved as a url, and run the same search again.  Opening the new search in a window side-by-side with the previous result will allow a quick visual comparison to see whether additional records have been found.  

It is possible that a new record is found (after correction, new data, etc) and a previous record is  no longer found (after correction, etc) which would mean that the total records would be the same.  

For MVP, this needs to be documented in the help (story #226).  For later development, a facility where the new data is flagged, is a nice-to-have.

**Comment by richardofsussex** [comment] 2023-01-06 13:26
Some of the core functionality has already been implemented – you can see your saved searches and your saved records, and you can run a saved search and compare the results with those you got when running the search before:
![image](https://user-images.githubusercontent.com/2197102/211019239-cf8bd6c4-5735-4997-ba37-61778cae5359.png)
I think it would be great to get this area of functionality fully working and tidied up.
This feature requires users to create a user id and log in (otherwise we have no means of logging "their" saved searches/records). We need to provide support for creating a "researcher" account (at present you have to volunteer as a transcriber to get access to this functionality), and that researchers are offered only appropriate menu options when they are logged in. Also, they need a set of navigation options _within_ the "saved searches" area - these are currently lacking. The "saved records" page needs a toolbar to export the records. (Arguably in this case - maybe in others too - it would be helpful to offer GEDCOM as a supported export format. The users could find records in FreeBMD2, export them as GEDCOM, and load them directly into other genealogical software/sites.)

**Comment by richardofsussex** [comment] 2023-01-11 17:30
@Vino-S I created a new branch for this issue based on the freebmd-development branch, but when I run it locally I don't see any opportunity to log in. I am able to log in on both test3 and beta. Is this because of code incompatibilities or is it caused by missing data files/collections?

**Comment by richardofsussex** [comment] 2023-01-25 17:10
To get a login dialogue, I need to run my local copy using the 127.0.0.1:3000 address and port. Previously I was using localhost:3000. Refinery treats 127.0.0.1 as a 'local request', but not localhost.

There is a researcher registration HTML page, but its style is different from the transcriber registration page, so I plan to replace it with code similar to that in the transcriber page. I will then attempt to trap requests to save a search or search result, and redirect them to this registration page (unless the user is already logged in).

**Comment by richardofsussex** [comment] 2023-02-13 17:43
Thanks to @Vino-S I have resolved my login issues. The user's Your Actions page appears, and includes Saved Entries and View Saved Searches. I can mark/save individual records in the detailed view, and their icon changes to a filled heart. However, when I select Saved Entries, I get an empty list. This code (in userid_detail.rb): 
![image](https://user-images.githubusercontent.com/2197102/218532020-9008a68c-1be4-4630-a769-0b34f09c4bb6.png)
is returning an empty list, despite being passed a set of hash values. [I've realised why - my bestguesshash table hasn't been updated to reflect the contents of my bestguess table! Subsequently I hand-updated the bestguesshash table with hash values picked out from the RubyMine debugger, and this worked perfectly.]
(The View Saved Searches function works fine.)

**Comment by richardofsussex** [comment] 2023-02-13 18:02
I see that one requirement above has already been implemented: the default value for _person_role_ is "researcher".

**Comment by richardofsussex** [comment] 2023-02-13 18:17
userid_details\new.html.erb says that form form_freebmd should be used for creating users in the FreeBMD project, but the corresponding form _form_freebmd.html.erb does not exist [in my development setup]. Do we need to create it?

**Comment by richardofsussex** [comment] 2023-02-13 18:33
We need a variant on search_queries/_count_and_tools_menu.html.erb which takes the saved_entries as its data source.

**Comment by DeniseColbert** [comment] 2023-02-21 15:41
Heart isn't getting filled on a click: not being saved?

**Comment by richardofsussex** [comment] 2023-03-06 12:54
I tried saving a search in test3 and got a "page not found" error. This doesn't happen in my local testing setup: I get a "search saved " message on the current page. @Vino-S, has branch fb_123_rbl been pushed to test3?

**Comment by richardofsussex** [comment] 2023-03-07 14:52
I have added the ability to export the saved records in GEDCOM format. The one field I haven't been able to include is sex. Here is an example of the output:
![image](https://user-images.githubusercontent.com/2197102/223458195-a18f6562-00b9-4f31-ae8c-6a45fa8fc9c4.png)

**Comment by richardofsussex** [comment] 2023-03-07 14:58
Note the URLs. These are patterned on the form of URLs used by FreeREG. The 'friendly' bit of the URL needs debugging: the quarter is missing. There is scope for including a textual summary of the entry as a NOTE - this could be like a citation. (Note that the WWW tag isn't an official part of GEDCOM 5.5.1, but it _is_ used by e.g. WikiTree.

**Comment by richardofsussex** [comment] 2023-03-16 16:21
@Vino-S I've just pushed this branch (fb_123_rbl), because I don't think I did that recently. Please check to see if my current code is in test3. Also, I would welcome advice on how to get the :sex field into my GEDCOM output. Thanks.

**Comment by Vino-S** [comment] 2023-07-11 13:49
ready for testing in test3

**Comment by richardofsussex** [comment] 2024-01-02 14:14
Save search leads to a "missing page" error (/search_queries/[UUID]/save_search), and clicking on the "Save entry" icon achieves nothing. The "Save as GEDCOM" menu item is there, but there is nothing to test it on ...

**Comment by richardofsussex** [comment] 2024-02-27 16:31
One observation as I get back into this issue: I don't think it will be possible to include a person's sex in the GEDCOM output, simply because FreeBMD doesn't record this information!

**Comment by richardofsussex** [comment] 2024-02-27 16:44
The District links in both the list of saved records and the entry details view for a saved record point to the UKBMD district page.

**Comment by richardofsussex** [comment] 2024-02-28 12:52
Fixed the District links so they now follow the same logic as other record views.

**Comment by richardofsussex** [comment] 2024-02-28 12:56
Saving a single record doesn't do anything. There should be a notification and it should appear in the list of saved records.

**Comment by richardofsussex** [comment] 2024-02-29 16:33
I have added the quarter to the `friendly_url` procedure in bestguess.rb:

![image](https://github.com/FreeUKGen/FreeBMD2/assets/2197102/264b170b-4590-4262-ab8e-8dfce129174c)

This will affect _all_ friendly URLs in the BMD2 site.

**Comment by richardofsussex** [comment] 2024-02-29 16:34
I notice that the District links in the side-by-side search comparison page are still pointing out to the UKBMD site: now fixed.

**Comment by richardofsussex** [comment] 2024-03-15 16:19
@Vino-S and I have worked out how to get the saving of records (and of searches) to actually work. Result (for saved records) is in test3.

**Comment by richardofsussex** [comment] 2024-03-19 15:35
Need to be able to 'unsave' a record by clicking on the heart icon again. @Vino-S to investigate (re-)implementing this.

**Comment by Vino-S** [comment] 2024-04-02 14:16
Ready for testing in test3

**Closed** 2024-04-16 15:05 UTC
Labels: upgraded user interface, frontend, backend, Developer, ready for deployment, Results page
